// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using thuongmaidientus1.Models;

#nullable disable

namespace WebKimCuong.Migrations
{
    [DbContext(typeof(DBContexts))]
    [Migration("20240628113711_modeldata")]
    partial class modeldata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("thuongmaidientus1.Models.CatMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("accountid")
                        .HasColumnType("int");

                    b.Property<string>("creatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.ToTable("CatMsts");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.CertifyMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Accountsid")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("orderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Accountsid");

                    b.ToTable("CertifyMsts");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("accountsid")
                        .HasColumnType("int");

                    b.Property<byte[]>("images")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("productsid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("accountsid");

                    b.HasIndex("productsid");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.CommentDescription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("accountid")
                        .HasColumnType("int");

                    b.Property<int?>("commentDescriptionsid")
                        .HasColumnType("int");

                    b.Property<int?>("commentid")
                        .HasColumnType("int");

                    b.Property<byte[]>("images")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.HasIndex("commentDescriptionsid");

                    b.HasIndex("commentid");

                    b.ToTable("commentDescriptions");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Danhgia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("accountid")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("productid")
                        .HasColumnType("int");

                    b.Property<int>("sao")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.HasIndex("productid");

                    b.ToTable("danhGias");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.DimMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Ordersid")
                        .HasColumnType("int");

                    b.Property<int?>("Productsid")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("total")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Ordersid");

                    b.HasIndex("Productsid");

                    b.ToTable("DimMsts");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.DimQltyMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DimQltyMst");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.GoldKrtMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("productid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("productid");

                    b.ToTable("GoldKrtMst");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Inquiry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("accountid")
                        .HasColumnType("int");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sodienthoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vanchuyenid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.HasIndex("vanchuyenid");

                    b.ToTable("Inquirys");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.ItemMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Categoryid")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Productid")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("Categoryid");

                    b.HasIndex("Productid");

                    b.ToTable("ItemMsts");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.JewelTypeMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Accountid")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<float?>("price")
                        .HasColumnType("real");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<string>("product_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.Property<int>("total")
                        .HasColumnType("int");

                    b.Property<string>("trangthai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vanchuyenid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Accountid");

                    b.HasIndex("vanchuyenid");

                    b.ToTable("JewelTypeMst");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Merchant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MerchantIpnUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantReturnUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantWebLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("merchants");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ExpireDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MerchantIdid")
                        .HasColumnType("int");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PaymentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PaymentDestinationIdid")
                        .HasColumnType("int");

                    b.Property<string>("PaymentLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentLastMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentRefId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("MerchantIdid");

                    b.HasIndex("PaymentDestinationIdid");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.PaymentDescription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("DesLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesSortIndex")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentIdid")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("ParentIdid");

                    b.ToTable("paymentDescriptions");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.PaymentNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("NotiAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotiContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotiDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotiMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotiResDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotiSatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotiSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentIdid")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentRefId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("PaymentIdid");

                    b.ToTable("paymentNotifications");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.PaymentSignature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("bit");

                    b.Property<int?>("PaymentIdid")
                        .HasColumnType("int");

                    b.Property<string>("SignAlgo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("SignDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SignOwn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("PaymentIdid");

                    b.ToTable("paymentSignatures");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PaymentIdid")
                        .HasColumnType("int");

                    b.Property<decimal?>("TranAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("TranDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TranMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranPayLoad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("PaymentIdid");

                    b.ToTable("paymentTransactions");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.ProdMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Accountsid")
                        .HasColumnType("int");

                    b.Property<int?>("Categorysid")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Shopsid")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("click")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Accountsid");

                    b.HasIndex("Categorysid");

                    b.HasIndex("Shopsid");

                    b.ToTable("ProdMsts");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.StoneMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Vanchuyenid")
                        .HasColumnType("int");

                    b.Property<int?>("shopid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Vanchuyenid");

                    b.HasIndex("shopid");

                    b.ToTable("StoneMsts");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Tokens", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("accountid")
                        .HasColumnType("int");

                    b.Property<string>("geneToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.ToTable("tokens");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.UserRegMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("Action")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CretorEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("roleid")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("roleid");

                    b.ToTable("UserRegMsts");
                });

            modelBuilder.Entity("WebKimCuong.Models.ChungnhanMst", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("chungNhans");
                });

            modelBuilder.Entity("WebKimCuong.Models.DimInfoMst", b =>
                {
                    b.Property<string>("DimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("DimCrt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimSubType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DimID");

                    b.ToTable("DimInfoMsts");
                });

            modelBuilder.Entity("WebKimCuong.Models.DimQltySubMst", b =>
                {
                    b.Property<string>("DimSubType_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("DimQlty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DimSubType_ID");

                    b.ToTable("DimQltySubMsts");
                });

            modelBuilder.Entity("WebKimCuong.Models.Motoi", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Motois");
                });

            modelBuilder.Entity("WebKimCuong.Models.StoneQltyMst", b =>
                {
                    b.Property<string>("StoneQlty_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StoneQlty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoneQlty_ID");

                    b.ToTable("StoneQltyMsts");
                });

            modelBuilder.Entity("WebKimCuong.Models.ThuonghieuMst", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThuonghieuMsts");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.CatMst", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.UserRegMst", "account")
                        .WithMany("Categories")
                        .HasForeignKey("accountid");

                    b.Navigation("account");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.CertifyMst", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.UserRegMst", "Accounts")
                        .WithMany("Orders")
                        .HasForeignKey("Accountsid");

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Comment", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.UserRegMst", "accounts")
                        .WithMany("Comments")
                        .HasForeignKey("accountsid");

                    b.HasOne("thuongmaidientus1.Models.ProdMst", "products")
                        .WithMany("Comments")
                        .HasForeignKey("productsid");

                    b.Navigation("accounts");

                    b.Navigation("products");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.CommentDescription", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.UserRegMst", "account")
                        .WithMany("commentDescriptions")
                        .HasForeignKey("accountid");

                    b.HasOne("thuongmaidientus1.Models.CommentDescription", "commentDescriptions")
                        .WithMany("commentDescriptionsList")
                        .HasForeignKey("commentDescriptionsid");

                    b.HasOne("thuongmaidientus1.Models.Comment", "comment")
                        .WithMany("commentDescriptions")
                        .HasForeignKey("commentid");

                    b.Navigation("account");

                    b.Navigation("comment");

                    b.Navigation("commentDescriptions");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Danhgia", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.UserRegMst", "account")
                        .WithMany("Danhgia")
                        .HasForeignKey("accountid");

                    b.HasOne("thuongmaidientus1.Models.ProdMst", "product")
                        .WithMany("Danhgia")
                        .HasForeignKey("productid");

                    b.Navigation("account");

                    b.Navigation("product");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.DimMst", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.CertifyMst", "Orders")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Ordersid");

                    b.HasOne("thuongmaidientus1.Models.ProdMst", "Products")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Productsid");

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.GoldKrtMst", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.ProdMst", "product")
                        .WithMany("ProductImages")
                        .HasForeignKey("productid");

                    b.Navigation("product");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Inquiry", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.UserRegMst", "account")
                        .WithMany("Shops")
                        .HasForeignKey("accountid");

                    b.HasOne("thuongmaidientus1.Models.DimQltyMst", "vanchuyen")
                        .WithMany("Shops")
                        .HasForeignKey("vanchuyenid");

                    b.Navigation("account");

                    b.Navigation("vanchuyen");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.ItemMst", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.CatMst", "Category")
                        .WithMany("CategoryProduct")
                        .HasForeignKey("Categoryid");

                    b.HasOne("thuongmaidientus1.Models.ProdMst", "Product")
                        .WithMany("CategoryProduct")
                        .HasForeignKey("Productid");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.JewelTypeMst", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.UserRegMst", "Account")
                        .WithMany("Xulydonhangs")
                        .HasForeignKey("Accountid");

                    b.HasOne("thuongmaidientus1.Models.DimQltyMst", "vanchuyen")
                        .WithMany("Vanchuyens")
                        .HasForeignKey("vanchuyenid");

                    b.Navigation("Account");

                    b.Navigation("vanchuyen");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Payment", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.Merchant", "MerchantId")
                        .WithMany("Payments")
                        .HasForeignKey("MerchantIdid");

                    b.HasOne("thuongmaidientus1.Models.PaymentDescription", "PaymentDestinationId")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentDestinationIdid");

                    b.Navigation("MerchantId");

                    b.Navigation("PaymentDestinationId");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.PaymentDescription", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.PaymentDescription", "ParentId")
                        .WithMany("PaymentDescriptions")
                        .HasForeignKey("ParentIdid");

                    b.Navigation("ParentId");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.PaymentNotification", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.Payment", "PaymentId")
                        .WithMany("PaymentNotifications")
                        .HasForeignKey("PaymentIdid");

                    b.Navigation("PaymentId");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.PaymentSignature", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.Payment", "PaymentId")
                        .WithMany("PaymentSignatures")
                        .HasForeignKey("PaymentIdid");

                    b.Navigation("PaymentId");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.PaymentTransaction", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.Payment", "PaymentId")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("PaymentIdid");

                    b.Navigation("PaymentId");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.ProdMst", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.UserRegMst", "Accounts")
                        .WithMany("Products")
                        .HasForeignKey("Accountsid");

                    b.HasOne("thuongmaidientus1.Models.CatMst", "Categorys")
                        .WithMany("Products")
                        .HasForeignKey("Categorysid");

                    b.HasOne("thuongmaidientus1.Models.Inquiry", "Shops")
                        .WithMany("Products")
                        .HasForeignKey("Shopsid");

                    b.Navigation("Accounts");

                    b.Navigation("Categorys");

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.StoneMst", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.DimQltyMst", "Vanchuyen")
                        .WithMany("ShopVanchuyens")
                        .HasForeignKey("Vanchuyenid");

                    b.HasOne("thuongmaidientus1.Models.Inquiry", "shop")
                        .WithMany("ShopVanchuyens")
                        .HasForeignKey("shopid");

                    b.Navigation("Vanchuyen");

                    b.Navigation("shop");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Tokens", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.UserRegMst", "account")
                        .WithMany()
                        .HasForeignKey("accountid");

                    b.Navigation("account");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.UserRegMst", b =>
                {
                    b.HasOne("thuongmaidientus1.Models.Roles", "role")
                        .WithMany("accounts")
                        .HasForeignKey("roleid");

                    b.Navigation("role");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.CatMst", b =>
                {
                    b.Navigation("CategoryProduct");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.CertifyMst", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Comment", b =>
                {
                    b.Navigation("commentDescriptions");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.CommentDescription", b =>
                {
                    b.Navigation("commentDescriptionsList");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.DimQltyMst", b =>
                {
                    b.Navigation("ShopVanchuyens");

                    b.Navigation("Shops");

                    b.Navigation("Vanchuyens");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Inquiry", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("ShopVanchuyens");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Merchant", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Payment", b =>
                {
                    b.Navigation("PaymentNotifications");

                    b.Navigation("PaymentSignatures");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.PaymentDescription", b =>
                {
                    b.Navigation("PaymentDescriptions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.ProdMst", b =>
                {
                    b.Navigation("CategoryProduct");

                    b.Navigation("Comments");

                    b.Navigation("Danhgia");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.Roles", b =>
                {
                    b.Navigation("accounts");
                });

            modelBuilder.Entity("thuongmaidientus1.Models.UserRegMst", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Comments");

                    b.Navigation("Danhgia");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Shops");

                    b.Navigation("Xulydonhangs");

                    b.Navigation("commentDescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
